#!/bin/bash
if [ "$BASH_SOURCE" = "$0" ]; then
    echo "This script can only be sourced."
    exit 1
fi

function title {
    echo -ne "\033]0;"$*"\007"
}

# Source .env files upon entering a directory
function source_env {
  if [ -f "$PWD/.env" ]; then
    source "$PWD/.env"
  fi
}

#function cd { 
#  builtin cd "$@" && source_env
#  [ -d "$PWD/.git" ] && title $(basename $PWD) || true
#}

function pushd { 
  builtin pushd "$@" && source_env
}

function popd { 
  builtin popd "$@" && source_env
}

function cdf {
  cd $(dirname $(find . -name $1))
}

function killjob {
	kill -9 $(jobs -p $1)
}

