tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "lightbend/tools"

brew "node"
brew "angular-cli"
brew "apache-flink"
brew "apache-spark"
brew "apache-zeppelin"
brew "python3"
brew "awscli"
brew "azure-cli"
brew "bash"
brew "bash-completion"
brew "brew-cask-completion"
brew "cython"
brew "cassandra"
brew "circleci"
brew "consul"
brew "curl"
brew "docker-completion"
brew "elasticsearch", restart_service: true
brew "exa"
brew "ffmpeg"
brew "fish"
brew "git"
brew "git-secrets"
brew "giter8"
brew "gradle"
brew "grafana", restart_service: true
brew "htop"
brew "iftop"
brew "jq"
brew "kafka"
brew "kafkacat"
brew "kibana", restart_service: true
brew "kubernetes-cli"
brew "kustomize"
brew "logstash", restart_service: true
brew "make"
brew "maven"
brew "minikube"
brew "mysql"
brew "nmap"
brew "node@10", link: true
brew "openvpn"
brew "operator-sdk"
brew "packer"
brew "packer-completion"
brew "pip-completion"
brew "postgresql"
brew "prometheus"
brew "protobuf"
brew "redis"
brew "sbt"
brew "scala"
brew "terraform"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"

cask "adoptopenjdk11"
cask "google-cloud-sdk"
cask "minikube"
cask "vagrant"
cask "virtualbox"
