#!/usr/bin/env bash

this_dir=$(cd $(dirname $0); pwd -P)
source=$this_dir/dotfiles
link="ln -svf"
arch=$(uname -s)
host=
email="michael@cramer.name"
skip_brew=false
skip_python=false
skip_dotfiles=false
shell="/usr/local/bin/fish"
exec=

while getopts ":tablp" opt; do
  case $opt in
    t)
      exec=echo ;;
    a)
      skip_brew=true
      skip_python=true
      skip_dotfiles=true ;;
    l)
      skip_dotfiles=true ;;
    b)
      skip_brew=true ;;
    p)
      skip_python=true ;;
    \?)
      echo "Invalid option: -$opt" >&2
      exit 1 ;;
    :)
      echo "Option -$opt requires an argument." >&2
      exit 1 ;;
  esac
done
shift $(($OPTIND - 1))


# Print section heading
heading() {
    char=${2:--}
    echo
#    printf "${char}%.0s" $(seq -3 ${#1})
    echo
    echo "${char} $1 ${char}"
#    printf "${char}%.0s" $(seq -3 ${#1})
    echo 
	echo
}

function install_brew_packages {
  heading "Installing brew packages... "
  
  brew=$(which brew) # witch brew?
  if [ -z "$brew" ]; then
    echo "First, installing brew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  else
    echo "Good, brew is installed..."
  fi
  $brew bundle 
}

install_python_modules() {
  heading "Installing python modules..."
  
  pip3 install -r $this_dir/python/requirements.txt
}

function handle_dotfile_directory {
  local base=$1
  local dir=$(basename $base)
  if [ ! -d $base ]; then
    echo "$base directory does not exist, skipping..."
    return
  fi

  pushd $base 1>/dev/null || return
  for file in $(find * -type f); do
    $exec mkdir -p $(dirname $HOME/.$dir/$file)
    $exec $link $base/$file $HOME/.$dir/$file
  done
  popd 1>/dev/null || return
}

function link_dotfiles {
  local base=$1
  if [ ! -d $base ]; then
    echo "$base directory does not exist, skipping..."
    return
  fi
  declare -A dotfiles

  echo "================================================================================"
  echo "--- Linking dotfiles in $1"

  # shellcheck disable=SC2044
  for file in $(find $base -mindepth 1 -maxdepth 1 -type f -not -name "arch-*" -exec basename {} ';'); do
    dotfiles[$HOME/.$file]=$base/$file
  done

  for type in $arch $host; do
    # shellcheck disable=SC2044
    for file in $(find $base -mindepth 1 -maxdepth 1 -type f -name "arch-$type.*" -exec basename {} ';'); do
      dotfiles[$HOME/${file#arch-$type*}]=$base/$file
    done
  done
  
  for dotfile in "${!dotfiles[@]}"; do
    $exec $link ${dotfiles[$dotfile]} $dotfile
  done
    
  for dir in $(find $base -mindepth 1 -maxdepth 1 -type d); do
    handle_dotfile_directory $dir
  done


  echo "--------------------------------------------------------------------------------"
  echo "--- Done with $base."
  echo
}

function config_misc {
  case $arch in
    Darwin)
	# First, read in the user headers, in case there's something already there...
	user_headers=$(defaults read com.apple.mail UserHeaders)
	if [ $user_headers -eq $email ]; then
		echo "Reply-To address already set to $email."
	else
		echo "Setting Reply-To address to $email."
		defaults write com.apple.mail UserHeaders '{"Reply-To" = "'$email'";}'
	fi
	echo "Setting Finder to show full path in title."
	defaults write com.apple.finder _FXShowPosixPathInTitle -bool true; killall Finder
      ;;
  esac
}

function config_powerline {

  cd $this_dir || return
  # First install powerline fonts
  git clone https://github.com/powerline/fonts.git --depth=1
  cd fonts
  ./install.sh
  cd ..
  rm -rf fonts
    # pip3 install powerline-status 
    powerline_location=$(pip3 show powerline-status | sed -E -n 's/^Location: (.+)/\1/p')

}

function main {
	heading "ENVironment deploYment" "#"

  if [ $SHELL != $shell ]; then
    echo "The user shell is set to $SHELL but should be $shell"
    if [ -z "$(grep "$shell" /etc/shells)" ]; then
      echo "Adding $shell to /etc/shells..."
      echo "$shell" | sudo tee -a /etc/shells
    fi
    chsh -s $shell
  fi

  # brew
  if [ "$skip_brew" == true ]; then
    echo "Skipping brew install..."
  else
    install_brew_packages
	fi

	# python
	if [ "$skip_python" == true ]; then
    echo "Skipping python install..."
  else
		install_python_modules
	fi

	# dotfiles
	if [ "$skip_dotfiles" == true ]; then
    echo "Skipping dotfile link..."
  else
		link_dotfiles $source
	fi

  config_powerline
}

# Run main if executed or exit if sourced
(return 0 2>/dev/null) || main 

# if [ -d "$vim_runtime" ]; then
#     echo "Vim runtime already exists at $vim_runtime."
# else
#     echo "Installing Vim runtime to $vim_runtime."
#     git clone --depth=1 https://github.com/amix/vimrc.git $vim_runtime
#     sh $vim_runtime/install_awesome_vimrc.sh
# fi
