#!/bin/bash
if [ "$BASH_SOURCE" = "$0" ]; then
    echo "This script can only be sourced."
    exit 1
fi

alias ..='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias less='less -r'
alias mkdir='mkdir -pv'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias search='grep -IRHn --color=auto'
alias h='history'
alias j='jobs -l'
alias path='echo -e ${PATH//:/\\n}'
alias svi='sudo vi'
#alias vis='vim "+set si"'
alias ping='ping -c 5'
alias pingfast='ping -c 100 -s.2'

case $(uname -s) in
    Linux)
	    alias ls='ls -F --color=auto'
        alias ll='ls -lF --color=auto'
        alias lla='ls -alF --color=auto'
        alias la='ls -aF --color=auto'
        alias l='ls -CF --color=auto'
	    alias l.='ls -d --color=auto .*'
	    alias listening='netstat -tlpn'        
        alias vi=vim
	;;

    Darwin)
	    alias ls='ls -FG'
        alias ll='ls -lFG'
        alias lla='ls -alFG'
        alias la='ls -aFG'
        alias l='ls -CFG'
	    alias l.='ls -dG .*'
	    alias now='date +"%T'
	    alias nowtime=now
	    alias nowdate='date +"%d-%m-%Y"'
	    alias listening='lsof -Pn -i4TCP -sTCP:LISTEN'
      alias vi=/usr/local/bin/vim
#	alias ipt='sudo /sbin/iptables'
#	alias iptlist='sudo /sbin/iptables -L -n -v --line-numbers'
#	alias iptlistin='sudo /sbin/iptables -L INPUT -n -v --line-numbers'
#	alias iptlistout='sudo /sbin/iptables -L OUTPUT -n -v --line-numbers'
#	alias iptlistfw='sudo /sbin/iptables -L FORWORD -n -v --line-numbers'
#	alias header='curl -I'
#	alias headerc='curl -I --compress'
#	alias root='sudo -i'
#	alias meminfo='free -m -l -t'
#	alias psmem='ps auxf | sort -nr -k 4'
#	alias psmem10='ps auxf | sort -nr -k 4 | head -10'
#	alias pscpu='ps auxf | sort -nr -k 3'
#	alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
#	alias cpuinfo='lscpu'
#	alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'
	;;
esac

alias vbm='VBoxManage'
alias pyjson='python -m json.tool'
