#!/bin/bash

if [ "$BASH_SOURCE" = "$0" ]; then
    echo "This script can only be sourced."
    exit 1
fi

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

##
## GENERAL OPTIONS 
##

# Prevent file overwrite on stdout redirection
# Use `>|` to force redirection to an existing file
set -o noclobber

# Update window size after every command
shopt -s checkwinsize

# Enable history expansion with space
# E.g. typing !!<space> will replace the !! with your last command
bind Space:magic-space

# Turn on recursive globbing (enables ** to recurse all directories)
shopt -s globstar 2> /dev/null

##
## HISTORY OPTIONS 
##

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL="erasedups:ignoreboth"

# Don't record some commands
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"

# Useful timestamp format
HISTTIMEFORMAT='%F %T '

# Huge history. Doesn't appear to slow things down, so why not?
HISTSIZE=500000
HISTFILESIZE=100000

# Append to the history file, don't overwrite it
shopt -s histappend

# Save multi-line commands as one command
shopt -s cmdhist

# Enable incremental history search with up/down arrows (also Readline goodness)
# Learn more about this here: http://codeinthehole.com/writing/the-most-important-command-line-tip-incremental-history-searching-with-inputrc/
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\e[C": forward-char'
bind '"\e[D": backward-char'

##
## TAB-COMPLETION (Readline bindings) 
##

# Display matches for ambiguous patterns at first tab press
bind "set show-all-if-ambiguous on"

##
## DIRECTORY NAVIGATION 
##

# Prepend cd to directory names automatically
shopt -s autocd 2> /dev/null

# Correct spelling errors during tab-completion
shopt -s dirspell 2> /dev/null

# Correct spelling errors in arguments supplied to cd
shopt -s cdspell 2> /dev/null

# This defines where cd looks for targets
# Add the directories you want to have fast access to, separated by colon
# Ex: CDPATH=".:~:~/projects" will look for targets in the current working directory, in home and in the ~/projects folder
CDPATH="."

# Make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Set up path
export PATH=/usr/bin:/usr/sbin:/bin:/sbin:$PATH	
case $(uname -s) in
	Linux)
		# Set additional path elements
		;;

	Darwin)
		CLICOLOR=1
		export LSCOLORS=Exfxcxdxbxegedabagacad

		# Enable bash completion for homebrew
		if [ -n "$(which brew)" ]; then
		    export PATH=/usr/local/bin:/usr/local/sbin:$PATH
            if [ -f $(brew --prefix)/etc/bash_completion ]; then
			    . $(brew --prefix)/etc/bash_completion
            fi
		fi
		;;
esac

# Load functions
if [ -e ~/.bash_functions ]; then
	. ~/.bash_functions
fi

# Load aliases
if [ -e ~/.bash_alias ]; then
	. ~/.bash_alias
fi

# Add scripts directory to path
if [ -d ~/envy/bin ]; then
    export PATH=$PATH:~/envy/bin
fi

# Add current directory to path
export PATH=$PATH:.

# Set JDK 
if [ -e ~/.jdk ]; then
	export JAVA_HOME=$(head -n 1 ~/.jdk | sed 's/.*\:[ \t]*//')
fi

# Set go
export PATH=$PATH:/usr/local/opt/go/libexec/bin

if [ -e /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk ]; then
	source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc
	source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc
fi

# Set powerline
if [ -d ~/Library/Python/2.7/bin ]; then
  export PATH=$PATH:~/Library/Python/2.7/bin
fi
powerline_path=$(python -c 'import pkgutil; print pkgutil.get_loader("powerline").filename' 2>/dev/null)
if [ -n "$powerline_path" ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  source ${powerline_path}/bindings/bash/powerline.sh
fi

# Enable travis stuff 
[ -f /Users/cramer/.travis/travis.sh ] && source /Users/cramer/.travis/travis.sh

# Local env 
[ -f ~/.bash_local ] && source ~/.bash_local

